Update php.yml

diff --git a/.github/workflows/php.yml b/.github/workflows/php.yml
--- a/.github/workflows/php.yml
+++ b/.github/workflows/php.yml
@@ -27,14 +27,14 @@ jobs:
     - name: Validate composer.json and composer.lock
       run: composer validate --strict 
   
-    - name: Cache Composer packages
-      id: composer-cache
-      uses: actions/cache@v3
-      with:
-        path: vendor
-        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
-        restore-keys: |
-          ${{ runner.os }}-php-
+    # - name: Cache Composer packages
+    #   id: composer-cache
+    #   uses: actions/cache@v3
+    #   with:
+    #     path: vendor
+    #     key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-php-
 
     - name: Install dependencies
       run: composer install --prefer-dist --no-progress --no-suggest
@@ -45,12 +45,12 @@ jobs:
     - name: Run PHPUnit tests
       run: vendor/bin/phpunit
 
-    - name: Check code coverage
-      run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml && bash <(curl -s https://codecov.io/bash)
+    # - name: Check code coverage
+    #   run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml && bash <(curl -s https://codecov.io/bash)
 
-    - name: Fail if coding standards or tests are not met
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Tests or coding standards check failed. Exiting."
-          exit 1
-        fi      
+    # - name: Fail if coding standards or tests are not met
+    #   run: |
+    #     if [ $? -ne 0 ]; then
+    #       echo "Tests or coding standards check failed. Exiting."
+    #       exit 1
+    #     fi      
